apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yourusername/your-repo.git'
    targetRevision: HEAD
    path: ./deployment.yaml  # adjust this path to where deployment.yaml is located
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
