apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/MaximePouce/42-Inception-of-MPouce.git'
    targetRevision: HEAD
    path: ./argo-conf  # directory name in the above repository
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
