apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: tgrivel/simple-web-app:1.0
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Pas l'temps d'niaiser :^)"
