apiVersion: v1
kind: service
metadata:
  name: app-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: app-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: tcp
    targetPort: 80
  selector:
    app: app
  sessionAffinity: None