apiVersion: v1
kind: Service
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-one
  sessionAffinity: None
