apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: tgrivel/simple-web-app:1.0
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Print: ici2"
