apiVersion: v1
kind: Service
metadata:
  name: app-two
  labels:
    app: app-two
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-two
  sessionAffinity: None
